// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7cc0f7d5-8363-4acf-8e1d-88c0d5d2fdc6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eAxa4DBfY",
    "aws_user_pools_web_client_id": "1eideorlp3f1k5jmnji420otra",
    "oauth": {}
};


export default awsmobile;
